apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trypipe
  name: trypipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trypipe
  template:
    metadata:
      labels:
        app: trypipe
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/trypipe/trypipe
          imagePullPolicy: Always
          name: trypipe
          ports:
            - containerPort: 8080
              protocol: TCP
