apiVersion: v1
kind: Service
metadata:
  labels:
    app: trypipe
  name: trypipe
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: trypipe
